
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplepubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplepubsub
  template:
    metadata:
      labels:
        app: samplepubsub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/unix-domain-socket-path: "/tmp/dapr-components-sockets"
        dapr.io/app-id: "samplepubsub"
        dapr.io/app-port: "5111"
        dapr.io/app-protocol: "http"
        dapr.io/sidecar-liveness-probe-delay-seconds: "10"
        dapr.io/sidecar-readiness-probe-delay-seconds: "1"
        dapr.io/sidecar-readiness-probe-timeout-seconds: "3"
    spec:
      volumes:
      - name: dapr-unix-domain-socket
        emptyDir: {}

      # SAT token used to authenticate between Dapr and the MQTT broker
      - name: sample-app-client-token
        projected:
          sources:
            - serviceAccountToken:
                path: sample-app-client-token
                audience: aio-mq-sample-app
                expirationSeconds: 86400

      # Certificate chain for Dapr to validate the MQTT broker
      - name: aio-ca-trust-bundle
        configMap:
          name: aio-ca-trust-bundle-test-only

      containers:
      # Container for the SamplePubSub C# Application 
      - name: samplepubsub
        image: __{container_registry}__/samplepubsub:__{image_version}__
        ports:
        - containerPort: 5111
        resources:
          requests:
            cpu: "0.1"
            memory: "100Mi"
          limits:
            cpu: "0.5"
            memory: "500Mi"

      # Container for the Pub/sub component
      - name: aio-mq-pubsub-pluggable
        image: ghcr.io/azure/iot-mq-dapr-components/pubsub:latest
        volumeMounts:
        - name: dapr-unix-domain-socket
          mountPath: /tmp/dapr-components-sockets
        - name: sample-app-client-token
          mountPath: /var/run/secrets/tokens
        - name: aio-ca-trust-bundle
          mountPath: /var/run/certs/aio-mq-ca-cert/
        resources:
          requests:
            cpu: "0.1"
            memory: "100Mi"
          limits:
            cpu: "0.5"
            memory: "500Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: samplepubsub-svc
  labels:
    app: samplepubsub
spec:
  selector:
    app: samplepubsub
  ports:
  - protocol: TCP
    port: 5111
    targetPort: 5111
  type: LoadBalancer