apiVersion: v1
kind: ServiceAccount
metadata:
  name: dapr-client
  namespace: azure-iot-operations
  annotations:
    aio-mq-broker-auth/group: dapr-workload
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-sample-app
  namespace: azure-iot-operations
spec:
  selector:
    matchLabels:
      app: mq-sample-app
  template:
    metadata:
      labels:
        app: mq-sample-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/inject-pluggable-components: "true"
        dapr.io/app-id: "mq-sample-app"
        dapr.io/app-port: "5111"
        dapr.io/app-protocol: "http"
    spec:
      serviceAccountName: dapr-client

      volumes:
      # SAT token used to authenticate between Dapr and the MQTT broker
      - name: mqtt-client-token
        projected:
          sources:
            - serviceAccountToken:
                path: mqtt-client-token
                audience: aio-mq
                expirationSeconds: 86400

      # Certificate chain for Dapr to validate the MQTT broker
      - name: aio-ca-trust-bundle
        configMap:
          name: aio-ca-trust-bundle-test-only

      containers:
      - name: mq-sample-app-container
        # image: __{container_registry}__/samplepubsub:__{image_version}__
        image: k3d-devregistry.localhost:5500/samplepubsub:0.3
        ports:
        - containerPort: 5111
        resources:
          requests:
            cpu: "0.1"
            memory: "100Mi"
          limits:
            cpu: "0.5"
            memory: "500Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: samplepubsub-svc
  namespace: azure-iot-operations
  labels:
    app: mq-sample-app
spec:
  selector:
    app: mq-sample-app
  ports:
  - protocol: TCP
    port: 5111
    targetPort: 5111
  type: LoadBalancer